'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
let model,store,currentPreset,selected,tab='function',mode='normal',state={},token=null,learningSeen=false,eventSource,lastEvent=0,epoch=null,view=[0,0,1440,1024],candidateRows=[],selectedCandidate='',nodes=new Map(),busy=false;
const levels={unknown:'À identifier',documented:'Documenté',observed:'Observé',confirmed:'Confirmé physiquement'};
const modeNames={normal:'Normal',modifier:'Avec modificateur',alpha:'ALPHA',monitor:'Monitoring',eq:'EQ',browse:'Chaîne de plugins',library:'Bibliothèque',params:'Paramètres DSP',nudge:'NUDGE',zoom:'Zoom'};
function el(tag,attrs={},text){const n=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')n.className=v;else n.setAttribute(k,v);}if(text!==undefined)n.textContent=text;return n;}
function svg(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))if(v!==undefined)n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
function tell(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
async function api(data){const r=await fetch('/api/console/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json();if(!r.ok||value.ok===false)throw Error(value.error||'Opération refusée');return value;}
async function run(fn){if(busy)return;busy=true;try{await fn();}catch(e){tell(e.message,true);}finally{busy=false;}}
function item(){return model?.elements.find(i=>i.id===selected);}
function validationLevel(i,dimension){if(dimension==='function'){const v=store.validations[i.id]?.functions?.[currentPreset]?.[mode];return v?.preset_revision===preset().revision?v.level:'unknown';}return store.validations[i.id]?.[dimension]?.level||i.validation[dimension];}
function preset(){return currentPreset==='ardour-current'?store.builtin:store.presets[currentPreset];}
function selectOptions(select,options,value){select.replaceChildren(...options.map(([v,t])=>el('option',{value:v},t)));select.value=value;}
function field(label,node){node.setAttribute('aria-label',label);const n=el('label',{},label);n.append(node);return n;}
function button(label,fn,cls='secondary'){const b=el('button',{type:'button',class:cls},label);b.addEventListener('click',()=>run(fn));return b;}
function help(text){return el('p',{class:'help'},text);}
function checkbox(text){const c=el('input',{type:'checkbox'}),l=el('label',{class:'check'},'');l.append(c,document.createTextNode(text));return [l,c];}
function code(value){return el('pre',{},typeof value==='string'?value:JSON.stringify(value,null,2));}
async function loadModel(keep=true){const r=await fetch('/api/console/model');if(!r.ok)throw Error('Impossible de charger la configuration');const data=await r.json();model=data.layout;store=data.store;if(!keep||!currentPreset||(currentPreset!=='ardour-current'&&!store.presets[currentPreset]))currentPreset=store.active.preset;if(!preset())currentPreset='ardour-current';renderPresets();draw();if(!selected)selected='button.1c.10';select(selected,false);}
function renderPresets(){selectOptions($('presets'),[[store.builtin.id,store.builtin.name+' · protégé'],...Object.values(store.presets).map(p=>[p.id,p.name+(p.adapter==='logic'?' · brouillon Logic':'')])],currentPreset);const p=preset();$('activePreset').textContent='Actif : '+store.active.name;$('presetName').value=p.name;$('presetName').disabled=p.protected;$('rename').disabled=p.protected;$('deletePreset').disabled=p.protected||store.active.preset===p.id;$('apply').disabled=p.adapter==='logic'||!!state.learning;$('rollback').disabled=!store.previous||!!state.learning;$('presetHint').textContent=p.adapter==='logic'?'Adaptateur Logic à venir ; application désactivée.':p.protected?'Comportement actuel conservé. Duplique pour personnaliser.':'Les modifications restent en brouillon jusqu’à l’application.';}
function draw(){nodes.clear();const root=$('surface');root.replaceChildren(svg('rect',{x:8,y:7,width:1424,height:1010,rx:18,class:'chassis'}));for(const s of model.sections){root.append(svg('rect',{x:s.box[0],y:s.box[1],width:s.box[2],height:s.box[3],rx:5,class:'panel'}),svg('text',{x:s.box[0]+12,y:s.box[1]+18,class:'section-label',textLength:s.id==='automation'?80:undefined,lengthAdjust:'spacingAndGlyphs'},s.label.toUpperCase()));}
for(const i of model.elements){if(i.kind==='reference')continue;const [x,y,w,h]=store.positions?.[i.id]||i.box;const g=svg('g',{'data-id':i.id,class:'control '+i.kind+(!i.input&&!i.output?' unknown':''),transform:`translate(${x} ${y})`,tabindex:'0',role:'button','aria-label':i.label});g.append(svg('title',{},i.label+' · '+i.id));
if(['display','clock'].includes(i.kind)){g.append(svg('rect',{width:w,height:h,rx:2,class:'display-bg'}),svg('text',{x:w/2,y:h/2,class:'display-text'},i.kind==='clock'?'00 00 00 00':'········'));}
else if(i.kind==='meter'){g.append(svg('rect',{width:w,height:h,rx:2,class:'meter-bg'}),svg('rect',{x:2,y:h-2,width:w-4,height:0,class:'meter-level'}));for(let n=1;n<14;n++)g.append(svg('line',{x1:0,y1:h*n/14,x2:w,y2:h*n/14,stroke:'#52665a','stroke-width':1}));}
else if(['encoder','knob','jog'].includes(i.kind)){g.append(svg('ellipse',{cx:w/2,cy:h/2,rx:w/2,ry:h/2,class:'knob'}));g.append(svg('line',{x1:w/2,y1:3,x2:w/2,y2:h*.23,stroke:'#b6bdae','stroke-width':2}));if(i.kind==='knob')g.append(svg('text',{x:w/2,y:h+9},i.label));if(i.kind==='jog')g.append(svg('circle',{cx:w*.35,cy:h*.23,r:11,fill:'#17221d'}));}
else if(i.kind==='ring'){g.append(svg('ellipse',{cx:w/2,cy:h/2,rx:w/2-3,ry:h/2-3,class:'ring'}));}
else if(i.kind==='fader'){g.append(svg('line',{x1:w/2,y1:2,x2:w/2,y2:h-2,class:'fader-rail'}));for(let n=0;n<9;n++)g.append(svg('line',{x1:0,y1:6+n*(h-12)/8,x2:7,y2:6+n*(h-12)/8,stroke:'#dbe1d4','stroke-width':1}));g.append(svg('rect',{x:5,y:h*.75,width:w-10,height:21,rx:2,class:'fader-cap'}));}
else if(i.kind==='pad'){g.append(svg('rect',{width:w,height:h,rx:3,class:'pad'}),svg('text',{x:w/2,y:15},'TRACKPAD'));}
else if(i.kind==='indicator'){g.append(svg('rect',{width:w,height:h,rx:2,class:'led'}));}
else {g.append(svg('rect',{width:w,height:h,rx:3,class:'shape'}));const text=i.label.replace('pre post assign mute','ASSIGN').replace('ChannelSelect','SELECT');g.append(svg('text',{x:w/2,y:h/2,'textLength':text.length>9?w-5:undefined,'lengthAdjust':'spacingAndGlyphs'},text.toUpperCase()));if(i.output)g.append(svg('rect',{x:w-7,y:3,width:4,height:3,rx:1,class:'led'}));}
// A ring leaves its central knob clickable.
if(i.kind==='ring')g.append(svg('ellipse',{cx:w/2,cy:h/2,rx:w/2-2,ry:h/2-2,fill:'none',stroke:'transparent','stroke-width':8,class:'ring-hit'}));else g.append(svg('rect',{x:-2,y:-2,width:w+4,height:h+4,rx:3,class:'hit'}));
root.append(g);nodes.set(i.id,{g,item:i,w,h});}
// Draw encoder knobs after their rings so both remain selectable.
for(const i of model.elements.filter(x=>x.kind==='encoder'))root.append(nodes.get(i.id).g);
selectOptions($('section'),[['all','Toute la console'],...model.sections.map(s=>[s.id,s.label])],$('section').value||'all');setView(view);paintState();}
function setView(v){const width=Math.max(220,Math.min(1800,v[2])),height=width*1024/1440;view=[Math.max(-100,Math.min(1440-width+100,v[0])),Math.max(-100,Math.min(1024-height+100,v[1])),width,height];$('surface').setAttribute('viewBox',view.join(' '));}
function zoom(f,cx=.5,cy=.5){const w=view[2]*f;setView([view[0]+(view[2]-w)*cx,view[1]+(view[3]-view[3]*f)*cy,w,view[3]*f]);}
function focusSection(id){const s=model.sections.find(s=>s.id===id);if(!s)return setView([0,0,1440,1024]);const [x,y,w,h]=s.box;const width=Math.max(w+60,(h+60)*1440/1024);setView([x+w/2-width/2,y+h/2-width*1024/1440/2,width,width*1024/1440]);}
function select(id,focus=false){if(!model.elements.some(i=>i.id===id))return;selected=id;for(const [key,n] of nodes)n.g.classList.toggle('selected',key===id);const i=item();$('elementSection').textContent=model.sections.find(s=>s.id===i.section).label.toUpperCase();$('elementTitle').textContent=i.label;$('elementId').textContent=id;if(focus){focusSection(i.section);$('section').value=i.section;}renderInspector();paintState();updateCandidates();}
function renderInspector(){const i=item(),body=$('inspectorBody');body.replaceChildren();if(!i)return;const p=preset();
if(tab==='function'){
const modes=el('select');selectOptions(modes,model.modes.map(m=>[m,modeNames[m]]),mode);modes.onchange=()=>{mode=modes.value;renderInspector();};body.append(field('Contexte de la console',modes));
const existing=p.bindings?.[i.id]?.[mode]||{kind:'inherit'};const kind=el('select');selectOptions(kind,[['inherit','Conserver le comportement existant'],['guided','Choisir une fonction existante'],['osc','OSC expert — arguments typés'],['disabled','Désactiver dans ce contexte']],existing.kind);kind.disabled=p.protected;body.append(field('Affectation',kind));
const area=el('div',{class:'function-fields'});body.append(area);let action,path,args,trigger;
function fields(){area.replaceChildren();if(kind.value==='guided'){action=el('select');selectOptions(action,Object.entries(store.guided),existing.action||'play');area.append(field('Fonction Ardour',action),help('Passe par les gestionnaires existants, avec les banques et protections de la Gateway.'));}
if(kind.value==='osc'){path=el('input',{placeholder:'/transport_play',value:existing.path||'/transport_play'});args=el('textarea',{'aria-label':'Arguments OSC typés'});args.value=JSON.stringify(existing.args||[{type:'i',value:1}],null,2);trigger=el('select');selectOptions(trigger,[['press','À l’appui'],['release','Au relâchement'],['both','Appui et relâchement'],['change','À chaque variation']],existing.trigger||'press');area.append(field('Chemin OSC',path),field('Déclenchement',trigger),field('Arguments JSON typés',args),help('Types : i (entier), f (décimal), s (texte). Utilise value pour une constante ou source : value, delta, pressed, channel, selected. Les /strip/* experts utilisent le SSID réel, pas le numéro de tranche. Destination : Ardour configuré.'));}
if(kind.value==='inherit'){area.append(help('Gestion native, avec les modes, modificateurs et banques actuels.'),code(i.functions?.[mode]??(i.input?'Gestion de la Gateway selon le contexte.':'Aucune entrée réseau établie pour cet élément.')));}}
kind.onchange=fields;fields();if(p.protected)body.append(help('Preset protégé. Le bouton Dupliquer crée ta version modifiable.'));else body.append(button('Enregistrer le brouillon',async()=>{const copy=structuredClone(p);copy.bindings[i.id]??={};let b={kind:kind.value};if(b.kind==='guided')b.action=action.value;if(b.kind==='osc'){b.path=path.value;b.trigger=trigger.value;b.args=JSON.parse(args.value);}copy.bindings[i.id][mode]=b;await api({action:'save',revision:store.revision,preset:p.id,data:copy});await loadModel();tell('Brouillon enregistré. Applique le preset pour l’utiliser.');}));
}else if(tab==='protocol'){
for(const [d,label] of [['input','Entrée depuis la console'],['output','Retour vers la console']]){const spec=store.protocol[i.id]?.[d]??i[d];body.append(el('h3',{},label),code(spec||'Encodage à identifier'),help('Validation : '+(store.validations[i.id]?.[d]?.level?levels[store.validations[i.id][d].level]:levels[i.validation[d]])));}
if(i.note)body.append(help(i.note));body.append(help('Pour une entrée, démarre la capture puis associe un candidat ci-dessous. Pour une sortie, saisis une adresse dans Essais, teste-la puis enregistre l’association.'));
const evidence=el('ul',{class:'evidence'});i.evidence.forEach(t=>evidence.append(el('li',{},t)));body.append(evidence);
}else if(tab==='test'){
body.append(help('Essai explicite, limité à deux secondes (moteur : une seconde). À la fin, la Gateway remet le retour courant.'));
const initial=store.protocol[i.id]?.output??i.output;const family=el('select');selectOptions(family,[['led','LED de bouton'],['meter','Vumètre'],['display','Afficheur'],['ring','Couronne'],['automation','LED automation'],['clock','Compteur'],['clock_mode','Unité du compteur'],['motor','Moteur de fader']],initial?.family||(i.kind==='meter'?'meter':'led'));
const address=el('input',{type:'number',min:0,max:127,value:initial?.address??10}),zone=el('input',{type:'number',min:0,max:28,value:initial?.zone??0}),key=el('input',{type:'number',min:0,max:63,value:initial?.key??0}),channel=el('input',{type:'number',min:1,max:8,value:initial?.channel??1});const fields=el('div',{class:'encoding-grid'});fields.append(field('Famille de sortie',family));const aw=field('Adresse décimale',address),zw=field('Zone décimale',zone),kw=field('Code décimal',key),cw=field('Tranche',channel);fields.append(aw,zw,kw,cw);body.append(fields);
function update(){aw.hidden=['led','motor'].includes(family.value);zw.hidden=kw.hidden=family.value!=='led';cw.hidden=family.value!=='motor';}family.onchange=update;update();function spec(){return family.value==='led'?{family:'led',zone:+zone.value,key:+key.value}:family.value==='motor'?{family:'motor',channel:+channel.value}:{family:family.value,address:+address.value};}
const [ml,mc]=checkbox('Essai moteur : fader libre, course limitée à 2,5 %');body.append(ml);const test=button('Lancer cet essai',async()=>{await api({action:'probe',element:i.id,encoding:spec(),motor_confirmed:mc.checked,delta:.025});tell('Essai envoyé par la Gateway. Observe l’élément physique avant de le valider.');});test.disabled=!state.online||!!state.learning;body.append(test,button('Arrêter l’essai',async()=>{await api({action:'probe_stop'});tell('Essai terminé ; retour courant restauré.');}));
const [ol,oc]=checkbox('Associer cette sortie à cet élément');body.append(ol,button('Enregistrer l’encodage de sortie',async()=>{await api({action:'protocol',revision:store.revision,element:i.id,direction:'output',encoding:spec(),confirmed:oc.checked});await loadModel();tell('Adresse enregistrée en préparation. Applique le preset pour activer la calibration.');}),help('L’association et la confirmation visuelle sont séparées. Les conflits d’adresses sont refusés.'));
}else{
for(const [dimension,label] of [['position','Emplacement'],['input','Encodage d’entrée'],['output','Retour physique'],['function','Fonction dans le logiciel']]){const value=validationLevel(i,dimension);const row=el('div',{class:'validation-row'});row.append(el('span',{},label),el('span',{class:'validation-badge'},levels[value]));body.append(row);}
const dim=el('select');selectOptions(dim,[['position','Emplacement'],['input','Encodage d’entrée'],['output','Retour physique'],['function','Fonction dans Ardour']],'position');const level=el('select');selectOptions(level,Object.entries(levels),'confirmed');const note=el('textarea',{placeholder:'Observation : élément vu, geste, résultat…',maxlength:500});const [cl,cc]=checkbox('J’ai personnellement observé cette validation');body.append(help('Fonction : '+p.name+' · '+modeNames[mode]+'. Une modification du preset demande une nouvelle validation.'),field('Ce que tu valides',dim),field('Niveau de preuve',level),field('Note',note),cl,button('Enregistrer la validation',async()=>{await api({action:'validation',revision:store.revision,element:i.id,dimension:dim.value,level:level.value,note:note.value,confirmed:cc.checked,preset:currentPreset,mode});await loadModel();tell('Validation enregistrée avec sa date et sa note.');}));
body.append(help('Un ACK prouve la réception réseau, pas le bon emplacement d’une LED ni le résultat d’une fonction.'));
const pos=el('details');pos.append(el('summary',{},'Corriger la position sur le dessin'));const xy=(store.positions?.[i.id]||i.box).map((v,j)=>el('input',{type:'number',value:v,min:0,max:j<2?1440:400,'aria-label':['X','Y','Largeur','Hauteur'][j]}));const grid=el('div',{class:'encoding-grid'});xy.forEach((n,j)=>grid.append(field(['X','Y','Largeur','Hauteur'][j],n)));pos.append(grid,button('Enregistrer la position',async()=>{await api({action:'position',revision:store.revision,element:i.id,box:xy.map(n=>+n.value)});await loadModel();tell('Position du dessin enregistrée.');}));body.append(pos);
}}
function paintState(){if(!model)return;const online=state.ok&&state.online;document.querySelector('.surface-panel').classList.toggle('stale',!online);$('connection').textContent=online?'● Console en ligne':'Console indisponible';$('connection').className='pill '+(online?'online':'offline');for(const [id,n] of nodes){const output=state.outputs?.[id],input=state.inputs?.[id];n.g.classList.toggle('on',!!output?.value);n.g.classList.toggle('active-input',input?.pressed===1&&Date.now()/1000-input.at<5);if(output){const t=n.g.querySelector('.display-text');if(t&&output.text!==undefined)t.textContent=output.text;const m=n.g.querySelector('.meter-level');if(m){const h=(n.h-4)*Math.max(0,Math.min(1,output.value||0));m.setAttribute('y',n.h-2-h);m.setAttribute('height',h);}const f=n.g.querySelector('.fader-cap');if(f&&output.value!==undefined)f.setAttribute('y',(n.h-21)*(1-output.value));}}
const inp=state.inputs?.[selected],out=state.outputs?.[selected];$('liveElement').textContent=!online?'État périmé — attendre la Gateway.':inp||out?[inp?'Entrée : '+inp.hex:null,out?'Retour : '+out.hex:null].filter(Boolean).join(' · '):'Aucun état reçu pour cet élément.';
const learning=state.learning;$('learningBar').classList.toggle('active',!!learning);$('learnStart').hidden=!!learning;$('learnStop').hidden=!learning;$('learnStop').disabled=!token;$('learnStart').disabled=!state.can_learn||!!learning;$('duration').disabled=!!learning;$('learningTitle').textContent=learning?'Capture isolée · '+Math.floor(learning.remaining/60)+':'+String(learning.remaining%60).padStart(2,'0'):'Apprendre sans agir';$('learningHint').textContent=learning?'Les gestes sont observés sans effet dans Ardour ni sur le PC. '+(token?'Cette page pilote la capture.':'Capture ouverte depuis une autre page.'):(state.can_learn?'Prêt. Transport arrêté et état Ardour récent.': 'En attente d’un transport arrêté, hors enregistrement, et d’un retour Ardour récent.');if(learning&&token)learningSeen=true;if(!learning&&token&&learningSeen)token=null;$('apply').disabled=preset()?.adapter==='logic'||!!learning;$('rollback').disabled=!store.previous||!!learning;
$('captureCount').textContent=(state.counters?.events||0)+' gestes reçus';}
function updateCandidates(){const rows=state.candidates||[];const old=$('candidates').value||selectedCandidate;candidateRows=rows;selectOptions($('candidates'),[['','Choisir un geste…'],...rows.map((r,i)=>[String(i),(r.element||'Non identifié')+' · '+r.hex+' · '+r.count+'×'])],old);if(!$('candidates').value)$('candidates').value='';candidateDetail();}
function candidateDetail(){selectedCandidate=$('candidates').value;const c=selectedCandidate!==''?candidateRows[+selectedCandidate]:null;$('candidateDetail').textContent=c?JSON.stringify(c,null,2):'Les gestes apparaîtront pendant une capture isolée.';$('associate').disabled=!c||!token||!selected||!$('associateConfirm').checked;}
function ingest(data){state=data;if(epoch&&epoch!==data.epoch){lastEvent=0;$('events').replaceChildren();tell('Gateway reconnectée. Les anciens gestes ne sont pas rejoués.');}epoch=data.epoch;paintState();updateCandidates();if(data.gap)$('streamNote').textContent='Historique partiel : des événements ont été regroupés ou dépassent la fenêtre conservée. Les états affichés sont les plus récents.';for(const e of data.events||[]){if(e.id<=lastEvent)continue;lastEvent=e.id;if(e.kind==='learning'&&e.active===false)tell('Capture terminée : '+e.reason+'. Aucun geste n’est rejoué.');const t=new Date(e.at*1000).toLocaleTimeString('fr-FR');const li=el('li',{},`${t} · ${e.element||e.kind} · ${e.hex||e.reason||e.preset||''}`);$('events').prepend(li);}while($('events').children.length>40)$('events').lastChild.remove();}
function connect(){eventSource?.close();eventSource=new EventSource('/api/console/events');eventSource.onmessage=e=>{try{ingest(JSON.parse(e.data));}catch(error){tell('État reçu illisible : '+error.message,true);}};eventSource.onerror=()=>{state={...state,ok:false,online:false,can_learn:false};paintState();};}
$('surface').addEventListener('click',e=>{if(dragged)return;const g=e.target.closest('[data-id]');if(g)select(g.dataset.id);});$('surface').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const g=e.target.closest('[data-id]');if(g){e.preventDefault();select(g.dataset.id);}}});
let drag=null,dragged=false;$('surface').addEventListener('pointerdown',e=>{dragged=false;if(e.target.closest('[data-id]'))return;drag={x:e.clientX,y:e.clientY,view:[...view]};$('surface').setPointerCapture(e.pointerId);});$('surface').addEventListener('pointermove',e=>{if(!drag)return;const rect=$('surface').getBoundingClientRect(),dx=(e.clientX-drag.x)*drag.view[2]/rect.width,dy=(e.clientY-drag.y)*drag.view[3]/rect.height;if(Math.abs(dx)+Math.abs(dy)>5)dragged=true;setView([drag.view[0]-dx,drag.view[1]-dy,...drag.view.slice(2)]);});$('surface').addEventListener('pointerup',()=>{drag=null;});$('surface').addEventListener('pointercancel',()=>{drag=null;});$('surface').addEventListener('wheel',e=>{e.preventDefault();const r=$('surface').getBoundingClientRect();zoom(e.deltaY>0?1.12:.89,(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height);},{passive:false});
$('zoomIn').onclick=()=>zoom(.75);$('zoomOut').onclick=()=>zoom(1.3);$('fit').onclick=()=>{$('section').value='all';setView([0,0,1440,1024]);};$('section').onchange=()=>focusSection($('section').value);
$('search').oninput=()=>{const q=$('search').value.toLocaleLowerCase('fr').trim();const results=$('searchResults');results.replaceChildren();results.hidden=!q;if(q)model.elements.filter(i=>(i.label+' '+i.id).toLowerCase().includes(q)).slice(0,40).forEach(i=>results.append(button(i.label,async()=>{select(i.id,true);results.hidden=true;$('search').value='';})));};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));renderInspector();});
$('presets').onchange=()=>{currentPreset=$('presets').value;renderPresets();renderInspector();};$('refresh').onclick=()=>run(async()=>{await loadModel();connect();tell('Configuration actualisée.');});
$('duplicate').onclick=()=>run(async()=>{const response=await api({action:'duplicate',preset:currentPreset,revision:store.revision});currentPreset=Object.keys(response.presets).find(id=>!store.presets[id]);await loadModel();tell('Copie créée. Tu peux maintenant modifier ses fonctions.');});
$('rename').onclick=()=>run(async()=>{const data={...preset(),name:$('presetName').value};await api({action:'save',preset:currentPreset,revision:store.revision,data});await loadModel();tell('Nom enregistré.');});
$('apply').onclick=()=>run(async()=>{await api({action:'activate',preset:currentPreset,revision:store.revision});await loadModel();tell('Preset et calibration appliqués. La version précédente est conservée.');});$('rollback').onclick=()=>run(async()=>{await api({action:'rollback',revision:store.revision});await loadModel(false);tell('Version précédente rétablie.');});
$('logic').onclick=()=>run(async()=>{const response=await api({action:'logic',revision:store.revision});currentPreset=Object.keys(response.presets).find(id=>!store.presets[id]);await loadModel();tell('Brouillon Logic créé. Il restera inactif jusqu’à l’ajout de l’adaptateur.');});$('deletePreset').onclick=()=>run(async()=>{await api({action:'delete',preset:currentPreset,revision:store.revision});currentPreset=null;await loadModel();tell('Brouillon supprimé.');});
$('exportPreset').onclick=()=>{const data={version:1,preset:preset()};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));const a=el('a',{href:url,download:preset().name.replace(/[^\w-]+/g,'-')+'.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('importPreset').onchange=()=>run(async()=>{const f=$('importPreset').files[0];if(!f)return;if(f.size>65500)throw Error('Preset trop grand (65 Ko maximum)');const data=JSON.parse(await f.text());const response=await api({action:'import',revision:store.revision,data});currentPreset=Object.keys(response.presets).find(id=>!store.presets[id]);await loadModel();tell('Preset importé en brouillon.');});
$('learnStart').onclick=()=>run(async()=>{const result=await api({action:'learn_start',seconds:+$('duration').value,element:selected});token=result.token;learningSeen=false;tell('Capture isolée démarrée. Manipule maintenant la console.');});$('learnStop').onclick=()=>run(async()=>{await api({action:'learn_stop',token});token=null;tell('Capture terminée. Le contrôle normal reprend sans rejouer les gestes.');});$('candidates').onchange=candidateDetail;$('associateConfirm').onchange=candidateDetail;$('associate').onclick=()=>run(async()=>{const c=candidateRows[+$('candidates').value];await api({action:'associate',token,element:selected,candidate_id:c.candidate_id,revision:store.revision,confirmed:$('associateConfirm').checked});await loadModel();$('associateConfirm').checked=false;tell('Entrée associée en préparation. Termine la capture puis applique le preset.');});
setInterval(async()=>{if(!token)return;try{await api({action:'learn_heartbeat',token});}catch(e){token=null;tell('Capture terminée : '+e.message,true);}},2000);
window.addEventListener('pagehide',()=>{if(token)navigator.sendBeacon('/api/console/action',new Blob([JSON.stringify({action:'learn_stop',token})],{type:'application/json'}));eventSource?.close();});
run(async()=>{await loadModel(false);connect();});
